version: '3.8'

services:
  web:
    build: .
    command: sh ./run_web_dev.sh
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - web_postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  web_postgres: