name: Deploy into Fandogh production

on:
  push:
    branches: [ main ]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        pyython-version: 3.8
    - name: Install dependencies
      run: |
        pip install fandogh_cli --upgrade

    - name: deploy db and django project
      env:
        FANDOGH_USERNAME: ${{ secrets.FANDOGH_USERNAME }}
        FANDOGH_PASSWORD: ${{ secrets.FANDOGH_PASSWORD }}
      run: |
        COLLECT_ERROR=1 fandogh login --username $FANDOGH_USERNAME --password $FANDOGH_PASSWORD
        fandogh service apply -f db-fandogh.yml
        fandogh source run